import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Skycast – Weather Now</title>
         <link rel="icon" href="/favicon.ico" type="image/x-icon" />
      </head>
      <body className={`${inter.variable} antialiased bg-sky-200`}>
        {children}
      </body>
    </html>
  );
}
